version: "3.8"
services:
  micado-interview-db:
    container_name: micado-interview-db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: micado
      POSTGRES_PASSWORD: myhandsaresweating
      POSTGRES_DB: micadointerview
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwd
    ports:
      - "5050:80"
